version: '3.9'

services:
  # Service Vue.js
  vuejs-app:
    image: kiurow590/opib-vue-js-front:latest
    container_name: vuejs-container
    environment:
      - 'VUE_APP_API=http://localhost:8090'  # URL de l'API
    ports:
      - "8091:80"  # Adaptez selon le port de votre application Vue.js
    volumes:
      - ~/data-externes:/app/public/pdf  # Monte le dossier XXX à l'extérieur
    restart: unless-stopped
    networks:
      - app-network

  # Service MySQL
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=opibdb'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '30037:3306'
    volumes:
      - mysql-data:/var/lib/mysql  # Volume pour persister les données MySQL
    networks:
      - app-network

volumes:
  data-externes:  # Volume pour les données externes du frontend
  mysql-data:  # Volume pour les données MySQL

networks:
  app-network:
    driver: bridge